MENU_FONT = 'ComicSansMS 20'
BUTTON_FONT = 'Helvetica 32 bold'
TITLE_FONT = 'Helvetica 27 bold'
NORM_FONT = 'Courier 20 bold'
EXIT_FONT = 'Helvetica 28'
NEWSTORY_FONT = 'ComicSansMS 19 bold'
OUTOUT_STORY_FONT = 'Times 17'
THEEND_FONT = 'Denmark 25 bold'